package yasc.gui;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class JSobre extends javax.swing.JDialog {

    public JSobre(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {
            this.htmlDevelopers.setPage(JSobre.class.getResource("html/Developers.html"));
        } catch (IOException ex) {
            Logger.getLogger(JSobre.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        htmlDevelopers = new yasc.gui.auxiliar.HtmlPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        htmlLicense = new yasc.gui.auxiliar.HtmlPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About Yasc");

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jLabel2.setText("<html>    <body>     <p  style=\"margin-left: 20px;\">The <strong>\"Yasc : Yes, a simulator's compiler\"</strong><br/> was developed and supported by<br/> </p>    <p style=\"margin-left: 50px;\">Instituto de Biociências, Letras e Ciências Exatas,</b></br>     <p style=\"margin-left: 50px;\">UNESP - Univ Estadual Paulista, campus de São José do Rio Preto,</b></br>     <p style=\"margin-left: 50px;\">Departamento de Ciências de Computação e Estatística (DCCE),</b></br>     <p style=\"margin-left: 50px;\">Laboratório do Grupo de Sistemas Paralelos e Distribuídos (GSPD).</b></br>     </body> </html>");
        jTabbedPane1.addTab("About", jLabel2);

        htmlDevelopers.setText("");
        jScrollPane1.setViewportView(htmlDevelopers);

        jTabbedPane1.addTab("Developers", jScrollPane1);

        jScrollPane2.setViewportView(htmlLicense);

        jTabbedPane1.addTab("License", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private yasc.gui.auxiliar.HtmlPane htmlDevelopers;
    private yasc.gui.auxiliar.HtmlPane htmlLicense;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
