package yasc.gui;

import yasc.Main;
import java.util.HashSet;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import yasc.gui.iconico.grade.DesenhoGrade;
import yasc.motor.carga.CargaConst;
import yasc.motor.carga.CargaRandom;
import yasc.motor.carga.GerarCarga;

public class SelecionaCargas extends javax.swing.JDialog {

    public SelecionaCargas(java.awt.Frame parent, boolean modal, GerarCarga gerarcarga, DesenhoGrade aDesenho) {
        super(parent, modal);
        this.carga = gerarcarga;
        initComponents();
        jCheckboxDistribuirIgual.setSelected(false);
        jRadioButton2Stage.setSelected(true);
        jRadioButtonPoisson.setSelected(false);
        jLabel2.setEnabled(false);
        jSpinnerAvgPoisson.setEnabled(false);
        jRadioButtonNormal.setSelected(false);
        jLabel3.setEnabled(false);
        jLabel8.setEnabled(false);
        jSpinnerAverageNormal.setEnabled(false);
        jSpinnerDesvPadNormal.setEnabled(false);
        this.setValores(gerarcarga);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRandom = new javax.swing.JPanel();
        jLabelNumberOfTasks = new javax.swing.JLabel();
        jSpinnerNumTarefas = new javax.swing.JSpinner();
        jSpinnerMed = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSpinnerAvgPoisson = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerMin = new javax.swing.JSpinner();
        jSpinnerAverageNormal = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        jSpinnerMax = new javax.swing.JSpinner();
        jSpinnerDesvPadNormal = new javax.swing.JSpinner();
        jRadioButton2Stage = new javax.swing.JRadioButton();
        jRadioButtonPoisson = new javax.swing.JRadioButton();
        jRadioButtonNormal = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jCheckboxDistribuirIgual = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jSpinnerTimeArrival = new javax.swing.JSpinner();
        jPanelUniform = new javax.swing.JPanel();
        jLabelNumberOfTasks1 = new javax.swing.JLabel();
        jSpinnerNumTarefasNo = new javax.swing.JSpinner();
        jSpinnerTam = new javax.swing.JSpinner();
        jLabel15 = new javax.swing.JLabel();
        jCheckBoxDistribuirIgual2 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        jSpinnerTimeArrival1 = new javax.swing.JSpinner();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        buttonGroupRandom = new javax.swing.ButtonGroup();
        jPanelModo = new javax.swing.JPanel();
        jRadioButtonUniform = new javax.swing.JRadioButton();
        jRadioButtonRandom = new javax.swing.JRadioButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPaneSelecionado = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jButtonOK1 = new javax.swing.JButton();

        jPanelRandom.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelRandom.setMaximumSize(null);
        jPanelRandom.setPreferredSize(new java.awt.Dimension(500, 300));

        jLabelNumberOfTasks.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelNumberOfTasks.setText(Main.languageResource.getString("Number of tasks")); // NOI18N

        jSpinnerNumTarefas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerMed.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jLabel1.setText(Main.languageResource.getString("Task size")); // NOI18N

        jLabel2.setText(Main.languageResource.getString("Average")); // NOI18N

        jSpinnerAvgPoisson.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1.0d, 0.1d));

        jLabel4.setText(Main.languageResource.getString("Minimum")); // NOI18N

        jLabel5.setText(Main.languageResource.getString("Break point")); // NOI18N

        jSpinnerMin.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jSpinnerAverageNormal.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, 1.0d, 0.1d));

        jLabel6.setText(Main.languageResource.getString("Maximum")); // NOI18N

        jSpinnerMax.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 1.0d));

        jSpinnerDesvPadNormal.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));

        buttonGroupRandom.add(jRadioButton2Stage);
        jRadioButton2Stage.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jRadioButton2Stage.setText("Two Stage Uniform");
        jRadioButton2Stage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2StageActionPerformed(evt);
            }
        });

        buttonGroupRandom.add(jRadioButtonPoisson);
        jRadioButtonPoisson.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jRadioButtonPoisson.setText("Poisson");
        jRadioButtonPoisson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPoissonActionPerformed(evt);
            }
        });

        buttonGroupRandom.add(jRadioButtonNormal);
        jRadioButtonNormal.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jRadioButtonNormal.setText("Normal");
        jRadioButtonNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNormalActionPerformed(evt);
            }
        });

        jLabel3.setText(Main.languageResource.getString("Average")); // NOI18N

        jLabel8.setText(Main.languageResource.getString("Standard deviation")); // NOI18N

        jCheckboxDistribuirIgual.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jCheckboxDistribuirIgual.setText(Main.languageResource.getString("Distribute loads randomly between ")); // NOI18N
        jCheckboxDistribuirIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckboxDistribuirIgualActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setText(Main.languageResource.getString("Time of arrival")); // NOI18N

        jSpinnerTimeArrival.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));

        javax.swing.GroupLayout jPanelRandomLayout = new javax.swing.GroupLayout(jPanelRandom);
        jPanelRandom.setLayout(jPanelRandomLayout);
        jPanelRandomLayout.setHorizontalGroup(
            jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRandomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRandomLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRandomLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRandomLayout.createSequentialGroup()
                                        .addComponent(jSpinnerAvgPoisson, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanelRandomLayout.createSequentialGroup()
                                        .addComponent(jSpinnerMin, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanelRandomLayout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addGap(251, 251, 251))))
                    .addGroup(jPanelRandomLayout.createSequentialGroup()
                        .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelRandomLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGap(89, 89, 89)
                                .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jSpinnerDesvPadNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanelRandomLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSpinnerAverageNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)))
                            .addComponent(jRadioButtonNormal))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelRandomLayout.createSequentialGroup()
                        .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton2Stage)
                            .addGroup(jPanelRandomLayout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel2))
                            .addComponent(jRadioButtonPoisson)
                            .addGroup(jPanelRandomLayout.createSequentialGroup()
                                .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNumberOfTasks, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSpinnerNumTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRandomLayout.createSequentialGroup()
                                        .addComponent(jSpinnerTimeArrival, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(24, 24, 24))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelRandomLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jSpinnerMax, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(30, 30, 30)
                                        .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jSpinnerMed, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelRandomLayout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addComponent(jCheckboxDistribuirIgual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelRandomLayout.setVerticalGroup(
            jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelRandomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRandomLayout.createSequentialGroup()
                        .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNumberOfTasks)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSpinnerNumTarefas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerTimeArrival, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCheckboxDistribuirIgual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButton2Stage)
                    .addGroup(jPanelRandomLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(jSpinnerMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jSpinnerMed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(3, 3, 3)
                .addComponent(jRadioButtonPoisson)
                .addGap(5, 5, 5)
                .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinnerAvgPoisson, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelRandomLayout.createSequentialGroup()
                        .addComponent(jRadioButtonNormal)
                        .addGap(51, 51, 51))
                    .addGroup(jPanelRandomLayout.createSequentialGroup()
                        .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelRandomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpinnerAverageNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSpinnerDesvPadNormal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanelUniform.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelUniform.setMaximumSize(null);
        jPanelUniform.setPreferredSize(new java.awt.Dimension(500, 300));

        jLabelNumberOfTasks1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabelNumberOfTasks1.setText(Main.languageResource.getString("Number of tasks")); // NOI18N

        jSpinnerNumTarefasNo.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        jSpinnerTam.setModel(new javax.swing.SpinnerNumberModel(0.0f, 0.0f, null, 1.0f));

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel15.setText(Main.languageResource.getString("Task size")); // NOI18N

        jCheckBoxDistribuirIgual2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jCheckBoxDistribuirIgual2.setText(Main.languageResource.getString("Distribute loads randomly between origination elements?")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setText(Main.languageResource.getString("Time of arrival")); // NOI18N

        jSpinnerTimeArrival1.setModel(new javax.swing.SpinnerNumberModel(0.0d, 0.0d, null, 0.1d));

        javax.swing.GroupLayout jPanelUniformLayout = new javax.swing.GroupLayout(jPanelUniform);
        jPanelUniform.setLayout(jPanelUniformLayout);
        jPanelUniformLayout.setHorizontalGroup(
            jPanelUniformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelUniformLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jCheckBoxDistribuirIgual2)
                .addGap(36, 36, 36))
            .addGroup(jPanelUniformLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelUniformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNumberOfTasks1)
                    .addComponent(jSpinnerNumTarefasNo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelUniformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jSpinnerTam, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(jPanelUniformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jSpinnerTimeArrival1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45))
        );
        jPanelUniformLayout.setVerticalGroup(
            jPanelUniformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUniformLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(jPanelUniformLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelUniformLayout.createSequentialGroup()
                        .addComponent(jLabelNumberOfTasks1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerNumTarefasNo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelUniformLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerTimeArrival1))
                    .addGroup(jPanelUniformLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerTam, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jCheckBoxDistribuirIgual2)
                .addGap(47, 47, 47))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Main.languageResource.getString("Random Workloads")); // NOI18N
        setMinimumSize(new java.awt.Dimension(550, 450));
        setResizable(false);

        jPanelModo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), Main.languageResource.getString("Insertion mode for the workloads"))); // NOI18N
        jPanelModo.setMaximumSize(new java.awt.Dimension(500, 60));
        jPanelModo.setMinimumSize(new java.awt.Dimension(500, 60));
        jPanelModo.setPreferredSize(new java.awt.Dimension(500, 60));

        jRadioButtonUniform.setText(Main.languageResource.getString("Uniform")); // NOI18N
        jRadioButtonUniform.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonUniformActionPerformed(evt);
            }
        });

        jRadioButtonRandom.setSelected(true);
        jRadioButtonRandom.setText(Main.languageResource.getString("Random")); // NOI18N
        jRadioButtonRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRandomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelModoLayout = new javax.swing.GroupLayout(jPanelModo);
        jPanelModo.setLayout(jPanelModoLayout);
        jPanelModoLayout.setHorizontalGroup(
            jPanelModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModoLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jRadioButtonRandom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jRadioButtonUniform, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );
        jPanelModoLayout.setVerticalGroup(
            jPanelModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelModoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelModoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonRandom)
                    .addComponent(jRadioButtonUniform))
                .addGap(9, 9, 9))
        );

        jButtonCancelar.setText(Main.languageResource.getString("Cancel")); // NOI18N
        jButtonCancelar.setMaximumSize(new java.awt.Dimension(80, 30));
        jButtonCancelar.setMinimumSize(new java.awt.Dimension(80, 30));
        jButtonCancelar.setPreferredSize(new java.awt.Dimension(80, 30));
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jScrollPaneSelecionado.setPreferredSize(new java.awt.Dimension(500, 300));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 498, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        jScrollPaneSelecionado.setViewportView(jPanel1);

        jButtonOK1.setText(Main.languageResource.getString("OK")); // NOI18N
        jButtonOK1.setPreferredSize(new java.awt.Dimension(80, 30));
        jButtonOK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOK1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(179, 179, 179)
                        .addComponent(jButtonOK1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPaneSelecionado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelModo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelModo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPaneSelecionado, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonOK1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRandomActionPerformed
        setTipo(GerarCarga.RANDOM);
    }//GEN-LAST:event_jRadioButtonRandomActionPerformed

    private void jRadioButtonUniformActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonUniformActionPerformed
        setTipo(GerarCarga.UNIFORM);
    }//GEN-LAST:event_jRadioButtonUniformActionPerformed

    private void jButtonOK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOK1ActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonRandom.isSelected()) {
            try {
                int numTaref = (Integer) jSpinnerNumTarefas.getValue();
                double avg = (double) jSpinnerMed.getValue();
                double max = (double) jSpinnerMax.getValue();
                double min = (double) jSpinnerMin.getValue();
                double avgPoisson = Double.parseDouble(jSpinnerAvgPoisson.getValue().toString());
                double avgNormal = Double.parseDouble(jSpinnerAverageNormal.getValue().toString());
                double DesvPad = Double.parseDouble(jSpinnerDesvPadNormal.getValue().toString());
                double ArrTime = Double.parseDouble(jSpinnerTimeArrival.getValue().toString());
                boolean distrIgual = jCheckboxDistribuirIgual.isSelected();
                int TipoDistr = 0;
                if (jRadioButton2Stage.isSelected()) {
                    TipoDistr = 0;
                } else if (jRadioButtonPoisson.isSelected()) {
                    TipoDistr = 1;
                } else if (jRadioButtonNormal.isSelected()) {
                    TipoDistr = 2;
                }
                this.carga = new CargaRandom(numTaref, min, max, avg, avgPoisson, avgNormal, DesvPad, TipoDistr, distrIgual, ArrTime);
            } catch (NumberFormatException ex) {
                Logger.getLogger(SelecionaCargas.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else if (jRadioButtonUniform.isSelected()) {
            try {
                int numeroTarefas = Integer.parseInt(jSpinnerNumTarefasNo.getValue().toString());
                double Tam = Double.parseDouble(jSpinnerTam.getValue().toString());
                boolean distrIgual = jCheckBoxDistribuirIgual2.isSelected();
                double ArrTime1 = Double.parseDouble(jSpinnerTimeArrival1.getValue().toString());
                this.carga = new CargaConst(numeroTarefas, Tam, distrIgual, ArrTime1);
            } catch (NumberFormatException ex) {
                Logger.getLogger(SelecionaCargas.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        this.setVisible(false);
    }//GEN-LAST:event_jButtonOK1ActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jRadioButton2StageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2StageActionPerformed
        // TODO add your handling code here:
        if (jRadioButton2Stage.isSelected()) {
            jLabel1.setEnabled(true);
            jLabel4.setEnabled(true);
            jLabel5.setEnabled(true);
            jLabel6.setEnabled(true);
            jSpinnerMin.setEnabled(true);
            jSpinnerMed.setEnabled(true);
            jSpinnerMax.setEnabled(true);
            jLabel3.setEnabled(false);
            jLabel8.setEnabled(false);
            jSpinnerAverageNormal.setEnabled(false);
            jSpinnerDesvPadNormal.setEnabled(false);
            jLabel2.setEnabled(false);
            jSpinnerAvgPoisson.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButton2StageActionPerformed

    private void jRadioButtonPoissonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPoissonActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonPoisson.isSelected()) {
            jLabel2.setEnabled(true);
            jSpinnerAvgPoisson.setEnabled(true);
            jLabel3.setEnabled(false);
            jLabel8.setEnabled(false);
            jSpinnerAverageNormal.setEnabled(false);
            jSpinnerDesvPadNormal.setEnabled(false);
            jLabel1.setEnabled(false);
            jLabel4.setEnabled(false);
            jLabel5.setEnabled(false);
            jLabel6.setEnabled(false);
            jSpinnerMin.setEnabled(false);
            jSpinnerMed.setEnabled(false);
            jSpinnerMax.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButtonPoissonActionPerformed

    private void jRadioButtonNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNormalActionPerformed
        // TODO add your handling code here:
        if (jRadioButtonNormal.isSelected()) {
            jLabel3.setEnabled(true);
            jLabel8.setEnabled(true);
            jSpinnerAverageNormal.setEnabled(true);
            jSpinnerDesvPadNormal.setEnabled(true);
            jLabel1.setEnabled(false);
            jLabel4.setEnabled(false);
            jLabel5.setEnabled(false);
            jLabel6.setEnabled(false);
            jSpinnerMin.setEnabled(false);
            jSpinnerMed.setEnabled(false);
            jSpinnerMax.setEnabled(false);
            jLabel2.setEnabled(false);
            jSpinnerAvgPoisson.setEnabled(false);
        }
    }//GEN-LAST:event_jRadioButtonNormalActionPerformed

    private void jCheckboxDistribuirIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckboxDistribuirIgualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckboxDistribuirIgualActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupRandom;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonOK1;
    private javax.swing.JCheckBox jCheckBoxDistribuirIgual2;
    private javax.swing.JCheckBox jCheckboxDistribuirIgual;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNumberOfTasks;
    private javax.swing.JLabel jLabelNumberOfTasks1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelModo;
    private javax.swing.JPanel jPanelRandom;
    private javax.swing.JPanel jPanelUniform;
    private javax.swing.JRadioButton jRadioButton2Stage;
    private javax.swing.JRadioButton jRadioButtonNormal;
    private javax.swing.JRadioButton jRadioButtonPoisson;
    private javax.swing.JRadioButton jRadioButtonRandom;
    private javax.swing.JRadioButton jRadioButtonUniform;
    private javax.swing.JScrollPane jScrollPaneSelecionado;
    private javax.swing.JSpinner jSpinnerAverageNormal;
    private javax.swing.JSpinner jSpinnerAvgPoisson;
    private javax.swing.JSpinner jSpinnerDesvPadNormal;
    private javax.swing.JSpinner jSpinnerMax;
    private javax.swing.JSpinner jSpinnerMed;
    private javax.swing.JSpinner jSpinnerMin;
    private javax.swing.JSpinner jSpinnerNumTarefas;
    private javax.swing.JSpinner jSpinnerNumTarefasNo;
    private javax.swing.JSpinner jSpinnerTam;
    private javax.swing.JSpinner jSpinnerTimeArrival;
    private javax.swing.JSpinner jSpinnerTimeArrival1;
    // End of variables declaration//GEN-END:variables
    private GerarCarga carga;
    private Vector<String> usuarios;

    GerarCarga getCargasConfiguracao() {
        return carga;
    }

    /**
     * Carrega os valores do gerador de cargas nos componentes da janela
     *
     * @param gerarcarga
     */
    private void setValores(GerarCarga gerarcarga) {
        if (gerarcarga != null) {
            switch (gerarcarga.getTipo()) {
                case GerarCarga.RANDOM:
                    CargaRandom random = (CargaRandom) gerarcarga;
                    jSpinnerNumTarefas.setValue(random.getNumeroTarefas());
                    jSpinnerMed.setValue(random.getAvg2());
                    jSpinnerMax.setValue(random.getMax());
                    jSpinnerMin.setValue(random.getMin());
                    jSpinnerAvgPoisson.setValue(random.getAvgPoisson());
                    jSpinnerDesvPadNormal.setValue(random.getDesvPad());
                    jSpinnerAverageNormal.setValue(random.getAvgNormal());
                    jSpinnerTimeArrival.setValue(random.getArrivalTime());
                    jCheckboxDistribuirIgual.setSelected(random.isDistribuirIgual());
                    setTipo(GerarCarga.RANDOM);
                    break;
                case GerarCarga.UNIFORM:
                    CargaConst _carga = (CargaConst) gerarcarga;
                    jSpinnerNumTarefasNo.setValue(_carga.getNumTars());
                    jSpinnerTam.setValue(_carga.getTam());
                    jSpinnerTimeArrival1.setValue(_carga.getArrivalTime());
                    jCheckBoxDistribuirIgual2.setSelected(_carga.isDistribuirIgual());
                    setTipo(GerarCarga.UNIFORM);
                    break;
            }
        } else {
            setTipo(GerarCarga.RANDOM);
            jRadioButton2Stage.setSelected(true);
            jRadioButtonPoisson.setSelected(false);
            jLabel2.setEnabled(false);
            jSpinnerAvgPoisson.setEnabled(false);
            jRadioButtonNormal.setSelected(false);
            jLabel3.setEnabled(false);
            jLabel8.setEnabled(false);
            jSpinnerAverageNormal.setEnabled(false);
            jSpinnerDesvPadNormal.setEnabled(false);
        }
    }

    public HashSet<String> getUsuarios() {
        return new HashSet<>(usuarios);
    }

    /**
     * Apresenta na janela jPanel e seta valores dos jRadioButton de acordo com
     * tipo informado
     *
     * @param tipo jRadioButton selecionado
     */
    private void setTipo(int tipo) {
        switch (tipo) {
            case GerarCarga.RANDOM:
                jRadioButtonUniform.setSelected(false);
                jRadioButtonRandom.setSelected(true);
                jScrollPaneSelecionado.setViewportView(jPanelRandom);
                break;
            case GerarCarga.UNIFORM:
                jRadioButtonUniform.setSelected(true);
                jRadioButtonRandom.setSelected(false);
                jScrollPaneSelecionado.setViewportView(jPanelUniform);
                break;
        }
    }
}
