package yasc.gui.entrada;

import yasc.Main;

public class Falhas extends javax.swing.JFrame {

    String stringCaminho;

    public Falhas(String caminho) {
        this.stringCaminho = caminho;
        initComponents();
        
        if (ListasArmazenamento.isFalha() && ListasArmazenamento.isFalhaCapacidade()) {
            jRadioButtonYes.setSelected(true);
            jRadioButtonCapacityNo.setSelected(true);
            setEnableFalha(true);
            jRadioButtonNo.setSelected(false);
            jRadioButtonCapacityYes.setSelected(true);
        } else if (ListasArmazenamento.isFalha() && !ListasArmazenamento.isFalhaCapacidade()) {
            jRadioButtonYes.setSelected(true);
            jRadioButtonCapacityYes.setSelected(false);
            setEnableFalha(true);
            jRadioButtonNo.setSelected(false);
            jRadioButtonCapacityNo.setSelected(false);
        } else {
            jRadioButtonYes.setSelected(false);
            jRadioButtonCapacityYes.setSelected(false);
            setEnableFalha(false);
            jRadioButtonNo.setSelected(true);
            jRadioButtonCapacityNo.setSelected(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        falha = new javax.swing.ButtonGroup();
        capacidade = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonCapacityYes = new javax.swing.JRadioButton();
        jRadioButtonCapacityNo = new javax.swing.JRadioButton();
        jButtonOk = new javax.swing.JButton();
        jRadioButtonYes = new javax.swing.JRadioButton();
        jRadioButtonNo = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Main.languageResource.getString("Failure and restrictions")); // NOI18N
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridLayout(1, 0));

        capacidade.add(jRadioButtonCapacityYes);
        jRadioButtonCapacityYes.setText(Main.languageResource.getString("Yes") ); // NOI18N
        jRadioButtonCapacityYes.setEnabled(false);
        jRadioButtonCapacityYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCapacityYesActionPerformed(evt);
            }
        });

        capacidade.add(jRadioButtonCapacityNo);
        jRadioButtonCapacityNo.setSelected(true);
        jRadioButtonCapacityNo.setText(Main.languageResource.getString("No") ); // NOI18N
        jRadioButtonCapacityNo.setEnabled(false);
        jRadioButtonCapacityNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCapacityNoActionPerformed(evt);
            }
        });

        jButtonOk.setText("Ok");
        jButtonOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOkActionPerformed(evt);
            }
        });

        falha.add(jRadioButtonYes);
        jRadioButtonYes.setText(Main.languageResource.getString("Yes") ); // NOI18N
        jRadioButtonYes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonYesActionPerformed(evt);
            }
        });

        falha.add(jRadioButtonNo);
        jRadioButtonNo.setSelected(true);
        jRadioButtonNo.setText(Main.languageResource.getString("No") ); // NOI18N
        jRadioButtonNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNoActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel2.setText(Main.languageResource.getString("There will be capacity restrictions?") ); // NOI18N
        jLabel2.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel1.setText(Main.languageResource.getString("Will the simulator be able to simulate failures") ); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jRadioButtonCapacityNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jRadioButtonCapacityYes, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jRadioButtonYes, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(jRadioButtonNo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButtonOk, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonYes, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonNo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCapacityYes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRadioButtonCapacityNo)
                .addGap(7, 7, 7)
                .addComponent(jButtonOk)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNoActionPerformed
        // TODO add your handling code here:
        setEnableFalha(false);
        ListasArmazenamento.setFalha(false);
    }//GEN-LAST:event_jRadioButtonNoActionPerformed

    private void jRadioButtonYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonYesActionPerformed
        // TODO add your handling code here:
        setEnableFalha(true);
        ListasArmazenamento.setFalha(true);
    }//GEN-LAST:event_jRadioButtonYesActionPerformed

    private void jRadioButtonCapacityYesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCapacityYesActionPerformed
        // TODO add your handling code here:
        ListasArmazenamento.setFalhaCapacidade(true);
    }//GEN-LAST:event_jRadioButtonCapacityYesActionPerformed

    private void jRadioButtonCapacityNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCapacityNoActionPerformed
        // TODO add your handling code here:
        ListasArmazenamento.setFalhaCapacidade(false);
    }//GEN-LAST:event_jRadioButtonCapacityNoActionPerformed

    private void jButtonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOkActionPerformed
        // TODO add your handling code here:
        EscolhaMetricas dialog = new EscolhaMetricas(stringCaminho);
        dialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                System.exit(0);
            }
        });
        this.setVisible(false);
        dialog.setVisible(true);

    }//GEN-LAST:event_jButtonOkActionPerformed

    private void setEnableFalha(boolean b) {
        jLabel2.setEnabled(b);
        jRadioButtonCapacityYes.setEnabled(b);
        jRadioButtonCapacityNo.setEnabled(b);
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup capacidade;
    private javax.swing.ButtonGroup falha;
    private javax.swing.JButton jButtonOk;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonCapacityNo;
    private javax.swing.JRadioButton jRadioButtonCapacityYes;
    private javax.swing.JRadioButton jRadioButtonNo;
    private javax.swing.JRadioButton jRadioButtonYes;
    // End of variables declaration//GEN-END:variables
}
